apiVersion: daemons.redhat.com/v1alpha1
kind: TangServer
metadata:
  name: tangserver-functional
  namespace: nbde
  finalizers:
  - finalizer.daemons.tangserver.redhat.com
spec:
  # Add fields here
  replicas: 1
  image: "registry.redhat.io/rhel9/tang"
  version: "latest"
  persistentVolumeClaim: "tangserver-pvc-main"
  serviceListenPort: 2222
