apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tangserver-pvc-functional1
  namespace: nbde
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tangserver-pvc-functional2
  namespace: nbde
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
