apiVersion: daemons.redhat.com/v1alpha1
kind: TangServer
metadata:
  name: tangserver-scaleup
  namespace: nbde
  finalizers:
  - finalizer.daemons.tangserver.redhat.com
spec:
  # Add fields here
  replicas: 1
  image: "registry.redhat.io/rhel8/tang"
  version: "latest"
  resourcesrequest:
    cpu: "40m"
    memory: "40M"
  resourceslimit:
    cpu: "60m"
    memory: "60M"
