apiVersion: daemons.redhat.com/v1alpha1
kind: TangServer
metadata:
  name: tangserver-functional1
  namespace: nbde
  finalizers:
  - finalizer.daemons.tangserver.redhat.com
spec:
  # Add fields here
  replicas: 1 
  image: "registry.redhat.io/rhel9/tang"
  version: "latest"
  persistentVolumeClaim: "tangserver-pvc-functional1"
  serviceListenPort: 3333
---
apiVersion: daemons.redhat.com/v1alpha1
kind: TangServer
metadata:
  name: tangserver-functional2
  namespace: nbde
  finalizers:
  - finalizer.daemons.tangserver.redhat.com
spec:
  # Add fields here
  replicas: 1
  image: "registry.redhat.io/rhel9/tang"
  version: "latest"
  persistentVolumeClaim: "tangserver-pvc-functional2"
  serviceListenPort: 4444
