apiVersion: daemons.redhat.com/v1alpha1
kind: TangServer
metadata:
  name: tangserver-main
  namespace: nbde
  finalizers:
  - finalizer.daemons.tangserver.redhat.com
spec:
  # Add fields here
  replicas: 3
  image: "registry.redhat.io/rhel8/tang"
  version: "latest"
  persistentVolumeClaim: "tangserver-pvc-main"
  serviceListenPort: 9999
